### ISSUE TITLE
第一次绑定完仓库token没有刷新请求

### ISSUE THREAD

**Issue by wss-git** [serverless-cd/serverless-cd#41]
![image](https://user-images.githubusercontent.com/56686088/228145708-c32e4330-bb8e-47cc-91e2-7f1889ec6494.png)

预期需要自动刷新一下 仓库名称 那一列的请求

还缺少了刷新按钮

**Comment by heimanba** [comment]
1. 刷新按钮，说白了是因为主题缺少 ICON font导致
2. 其实是BUG ，需要 晨哥的组件解决
