### ISSUE TITLE
worker 函数不再交互数据库

### ISSUE THREAD

**Issue by wss-git** [serverless-cd/serverless-cd#42]
worker 不再和数据库交互，而是通过 api 请求到 admin 函数下进行修改

带来的好处：
- 彻底实现数据库维护在一处
- 将 worker 分离出去，不再是项目的不可分离的核心

可能遇到问题：
- 数据请求失败了要不要影响流水线？
- 请求的处理时长不一，有没有可能说 running 在 success 之后？ （串行不会存在这个问题，并行可能会存在）

**Comment by heimanba** [comment]
首先worker应该只是去写 Task相关的数据，
1. `数据请求失败`我理解为：写入Task失败？这里首先要做好重试的机制，其次之前的设计里面其实是 complete的操作不影响整个流水线的行为。可以看作是系统的事件。但是这样其实需要把  `部署状态` 进行修改过来
2. `请求的处理时长不一` 没有太看懂

**Comment by wss-git** [comment]
> worker 不再和数据库交互，而是通过 api 请求到 admin 函数下进行修改
> 
> 带来的好处：
> 
> * 彻底实现数据库维护在一处
> * 将 worker 分离出去，不再是项目的不可分离的核心
> 
> 可能遇到问题：
> 
> * 数据请求失败了要不要影响流水线？
> * 请求的处理时长不一，有没有可能说 running 在 success 之后？ （串行不会存在这个问题，并行可能会存在）

还有日志读存问题

**Comment by wss-git** [comment]
整理一下梳理遇到的问题：
1. 鉴权问题：控制台重新部署还好，直接使用登陆用户的鉴权 但是从web触发过来使用谁的权限呢？经梳理数据结构有两个选择：
选择一：这个应用创建者权限，理由：这个应用本来就是这个人创建，从 github 算是他的操作也没有什么说不过去的。
选择二：这个组织的创建者权限，理由：使用的密钥什么信息是都关联的创建者团队的那条数据，使用它也说的过去

2. 日志写入问题：
如果 worker 后面和 admin 不在一个账户下运行，那么日志写在哪里呢？各自怎么读呢？
部署 admin 的账号下，就需要用户频繁的给我们 push 日志，到 admin 怎么写和读和现在就一样了嘛
用户账号下，写和目前一样，就是读取的链路能会长一些。需要 worker 暴露一些接口，让我们来调用返回接口。

**Comment by wss-git** [comment]
> 整理一下梳理遇到的问题：
> 
> 1. 鉴权问题：控制台重新部署还好，直接使用登陆用户的鉴权 但是从web触发过来使用谁的权限呢？经梳理数据结构有两个选择：
>    选择一：这个应用创建者权限，理由：这个应用本来就是这个人创建，从 github 算是他的操作也没有什么说不过去的。
>    选择二：这个组织的创建者权限，理由：使用的密钥什么信息是都关联的创建者团队的那条数据，使用它也说的过去
> 2. 日志写入问题：
>    如果 worker 后面和 admin 不在一个账户下运行，那么日志写在哪里呢？各自怎么读呢？
>    部署 admin 的账号下，就需要用户频繁的给我们 push 日志，到 admin 怎么写和读和现在就一样了嘛
>    用户账号下，写和目前一样，就是读取的链路能会长一些。需要 worker 暴露一些接口，让我们来调用返回接口。

1. 应用创建这个权限
2. worker 函数下
