### ISSUE TITLE
【BUG】0403 体验问题

### ISSUE THREAD

**Issue by heimanba** [serverless-cd/serverless-cd#49]
- [x] 重新部署跳转到无权限页面

![image](https://user-images.githubusercontent.com/5129967/229511897-4bc7adaa-3acf-416c-9735-0b6eb3a9e539.png)

**Comment by heimanba** [comment]
- [ ] 部署状态ICON不存在

![image](https://user-images.githubusercontent.com/5129967/229512130-db5fadc4-5b81-4048-8a6c-e21381b4de65.png)

**Comment by heimanba** [comment]
- [ ] 仓库代码绑定失败

![image](https://user-images.githubusercontent.com/5129967/229513249-5797800e-55c1-4315-b8f8-867da0007c65.png)

**Comment by heimanba** [comment]
- [ ] 运维管理
![image](https://user-images.githubusercontent.com/5129967/229514829-e53a91c0-fdca-4e6c-9c70-eefb58583310.png)
![image](https://user-images.githubusercontent.com/5129967/229514877-4839cb42-3f7c-434b-9692-95a57c135bfe.png)

**Comment by heimanba** [comment]
- 最新提交  commit Tab框有点大
![image](https://user-images.githubusercontent.com/5129967/229519510-db563ba8-e86e-4f3e-8478-c8ed4c99185f.png)

**Comment by heimanba** [comment]
- [ ] 应用概览加上部署历史
![image](https://user-images.githubusercontent.com/5129967/229520936-f76c7191-786b-4360-ba2d-cc17a21abfa4.png)

1. 区分本地部署 & GitHub触发
![image](https://user-images.githubusercontent.com/5129967/229521345-fcb48544-98ba-490b-8617-489f26a2eebb.png)

2. 本地部署 不能进去详情
![image](https://user-images.githubusercontent.com/5129967/229521706-03daa336-a9be-4194-a564-13be3a747f91.png)

**Comment by heimanba** [comment]
- [ ] Button样式
![image](https://user-images.githubusercontent.com/5129967/229522090-591e6672-ff59-4ad4-a28c-914357db2427.png)

**Comment by heimanba** [comment]
-  文案修改
![image](https://user-images.githubusercontent.com/5129967/229525882-db8ee661-6f61-44e0-84f8-6efc7b173de4.png)

**Comment by wss-git** [comment]
> * [x]  重新部署跳转到无权限页面
> 
> ![image](https://user-images.githubusercontent.com/5129967/229511897-4bc7adaa-3acf-416c-9735-0b6eb3a9e539.png)

路由重定向存在问题，已修复

**Comment by g-fengchen** [comment]
> * [x]  部署状态ICON不存在
> 
> ![image](https://user-images.githubusercontent.com/5129967/229512130-db5fadc4-5b81-4048-8a6c-e21381b4de65.png)

初始化status获取失败导致icon丢失，已修复

**Comment by wss-git** [comment]
- [] Task 新增 trigger_type 字段。取值如下

```
console: 控制台发出的动作
  manual
  redeploy
  rollback

provider: 走的我们的webhook触发器
  github
  gitee
  codeup
  gitlab

tracker:
  -app_center-
  -serverless_cd-
  cloud_shell
  yunxiao
  github
  gitlab
  jenkins
  darwin
  ...
```

- [] 关联需求，前端调用 /api/dispatch/redeploy 需要新增一个 triggerType 参数

**Comment by wss-git** [comment]
- [ ] 应用名称需要显示出来

**Comment by wss-git** [comment]
> * trigger_type

list task 请求新增 triggerType 参数控制触发类型：
取值 `webhook` 、`console` 、`tracker `, 默认是返回所有
```
fetch('/api/task/list?appId=xxxx&envName=default&orgName=wss&triggerType=webhook')
```

**Comment by heimanba** [comment]
- [ ] 文案修改

![image](https://user-images.githubusercontent.com/5129967/229838489-2e85e25d-2570-4d27-a977-5272add61896.png)

**Comment by wss-git** [comment]
- [ ] 创建页面存在问题
![image](https://user-images.githubusercontent.com/56686088/230252381-c5e2634a-b440-4c4a-af91-7c4eb114a59e.png)

**Comment by wss-git** [comment]
- [ ]
![image](https://user-images.githubusercontent.com/5129967/229525171-1ef3596e-7ccc-468e-8eae-76396876abfd.png)

**Comment by wss-git** [comment]
- [ ] 
![image](https://user-images.githubusercontent.com/5129967/229525234-55af8984-124d-484a-8949-774768029e07.png)

**Comment by wss-git** [comment]
> * [x]  运维管理
>   ![image](https://user-images.githubusercontent.com/5129967/229514829-e53a91c0-fdca-4e6c-9c70-eefb58583310.png)
>   ![image](https://user-images.githubusercontent.com/5129967/229514877-4839cb42-3f7c-434b-9692-95a57c135bfe.png)

数据已经可以显示在页面了，但是如果说需要和调用或者等能力需要有ak支持

**Comment by g-fengchen** [comment]
-[ ] /api/dispatch/manual 接口调用失败
![image](https://user-images.githubusercontent.com/111403549/230317004-7064ecfc-9279-4ac4-ab2a-18f184e6d429.png)

{
    "code": "Invalid",
    "success": false,
    "message": "获取 github 信息失败: HttpError: No commit found for SHA: refs/heads/serverless-cd-project-setup"
}

**Comment by heimanba** [comment]
- 点击新建完团队后跳转到无权限的页面
![image](https://user-images.githubusercontent.com/5129967/230431748-9d83763a-140f-442d-956c-97bec642a64a.png)
