### ISSUE TITLE
云账号管理设计

### ISSUE THREAD

**Issue by wss-git** [serverless-cd/serverless-cd#56]
### （团队）
```
org: { # 加密
  cloud_secret: {
    dankun: {
      AccessKeyID:     LTA******************Ntx
      AccessKeySecret: pcw************************Eww
      AccountID:       174**********624
      provider: xxxx
    },
    wss: {
      ak: xx,
      sk: yyy,
      provider: xxxx
    }
  }
}
```
### 应用环境
```
env: {
  cloudAlias: dankun
}
```

## 交互

![image](https://user-images.githubusercontent.com/5129967/230532669-062a134c-08ab-4163-9b65-32f114fabeba.png)

![image](https://user-images.githubusercontent.com/5129967/230534008-14d44da6-2f40-4eab-8f57-1e57146c6c7d.png)

![image](https://user-images.githubusercontent.com/5129967/230533040-3a29e1b6-a723-4c86-8652-c021038b7385.png)

## engine执行时候, cloudSecrets 如何应用起来
1. Engine.start会注入： cloudSecrets 字段
2. 日志：cloudSecrets 字段和Secret 类似，需要变成 *** @华力 # 解密
```
AccessKeyID:     LTA******************id7
AccessKeySecret: 1sN************************1D6
AccountID:       164**********023
```

## 添加密钥相关

![image](https://user-images.githubusercontent.com/5129967/230535925-fcf64d7f-6225-4f72-af15-b4a96fa7dc73.png)

**Comment by wss-git** [comment]
engine 接受 inputs.cloudSecrets  字段

**Comment by xsahxl** [comment]
> engine 接受 inputs.cloudSecrets 字段
```ts
   const engine = new Engine({
      steps,
      logConfig: { logPrefix },
      inputs: { cloudSecrets: { name: 'xiaoming', long: 'iamxiaoming' } },
    });
    const res = await engine.start();
```

**Comment by wss-git** [comment]
- [ ]
