### ISSUE TITLE
410 issue

### ISSUE THREAD

**Issue by wss-git** [serverless-cd/serverless-cd#58]
- [x] 存在一个 /api/application/list 死循环请求接口
![image](https://user-images.githubusercontent.com/56686088/230820227-d8ba6feb-c3a8-4b19-b569-6fed7ba54eba.png)

**Comment by g-fengchen** [comment]
- [ ]
![image](https://user-images.githubusercontent.com/111403549/230820511-2a81250c-9b20-4259-8472-1356988db1b7.png)
触发方式给个icon？

**Comment by g-fengchen** [comment]
- [ ] 授权过期，显示在仓库用户下
- 
![image](https://user-images.githubusercontent.com/111403549/230820597-342a6202-cfaf-4683-af74-48b06f937f4d.png)

**Comment by wss-git** [comment]
- [ ] 在团队内缺少浏览者角色

**Comment by wss-git** [comment]
- [ ] 修改完团队角色需要手动刷新才有效

**Comment by wss-git** [comment]
- [ ] 修改团队角色，然后点击刷新列表，再点击修改角色
![image](https://user-images.githubusercontent.com/56686088/230831167-b0dfdc12-474e-444e-88da-8412519ea686.png)

**Comment by wss-git** [comment]
- [ ]

**Comment by heimanba** [comment]
本地启动 `make start`, 不依赖当前 `.env`,提供默认的 `env环境`
- 默认使用sqlite,存储在`.tmp/data.db`中
- 默认的JWT_SECRET

**Comment by wss-git** [comment]
- [ ] 没有找到 不应是 loading，error 或者 disable 都可
![image](https://user-images.githubusercontent.com/56686088/230884707-818372bb-763a-4b72-8475-303603293442.png)

**Comment by wss-git** [comment]
- [ ] 创建应用时需要关联云账号。获取方式 org 下面有个 cloud_secret 字段

![](https://user-images.githubusercontent.com/5129967/230534008-14d44da6-2f40-4eab-8f57-1e57146c6c7d.png)

**Comment by wss-git** [comment]
- [ ] 云账号配置需要 accoundId

**Comment by wss-git** [comment]
- [ ] latest biao标签不应该显示回滚，而是重新部署 
![image](https://user-images.githubusercontent.com/56686088/231047102-d4490772-e76d-4afd-a570-644bfcda087c.png)

**Comment by wss-git** [comment]
- [ ] 触发分支没有了
![Uploading image.png…]()

**Comment by heimanba** [comment]
- [ ] 应用详情 关联云账号 需要新增和编辑能力

![image](https://user-images.githubusercontent.com/5129967/231147112-b7ffeb18-4d4a-4c5f-9c2d-4685c504b94a.png)

**Comment by heimanba** [comment]
- [ ] 点击环境名称 进不去

![image](https://user-images.githubusercontent.com/5129967/231158345-19bd74fe-e1a1-44e5-8408-360b50797f97.png)
